TOKENS = {
    "abstract": "ABSTRACT",
    "assert": "ASSERT",
    "boolean": "BOOLEAN",
    "break": "BREAK",
    "byte": "BYTE",
    "case": "CASE",
    "catch": "CATCH",
    "char": "CHAR",
    "class": "CLASS",
    "const": "CONST",
    "continue": "CONTINUE",
    "default": "DEFAULT",
    "do": "DO",
    "double": "DOUBLE",
    "else": "ELSE",
    "extends": "EXTENDS",
    "false": "FALSE",
    "final": "FINAL",
    "finally": "FINALLY",
    "float": "FLOAT",
    "for": "FOR",
    "goto": "GOTO",
    "if": "IF",
    "implements": "IMPLEMENTS",
    "import": "IMPORT",
    "instanceof": "INSTANCEOF",
    "int": "INT",
    "interface": "INTERFACE",
    "long": "LONG",
    "native": "NATIVE",
    "new": "NEW",
    "null": "NULL",
    "package": "PACKAGE",
    "private": "PRIVATE",
    "protected": "PROTECTED",
    "public": "PUBLIC",
    "return": "RETURN",
    "short": "SHORT",
    "static": "STATIC",
    "strictfp": "STRICTFP",
    "super": "SUPER",
    "switch": "SWITCH",
    "synchronized": "SYNCHRONIZED",
    "this": "THIS",
    "throw": "THROW",
    "throws": "THROWS",
    "transient": "TRANSIENT",
    "true": "TRUE",
    "try": "TRY",
    "void": "VOID",
    "volatile": "VOLATILE",
    "while": "WHILE",

    // aritimetico
    "+": "ADD",
    "-": "SUBTRACT",
    "*": "MULTIPLY",
    "/": "DIVIDE",
    "%": "MODULO",
    "++": "INCREMENT",
    "--": "DECREMENT",

    // operadores de atribuição

    "=": "ASSIGN",
    "+=": "ADD_ASSIGN",
    "-=": "SUBTRACT_ASSIGN",
    "*=": "MULTIPLY_ASSIGN",
    "/=": "DIVIDE_ASSIGN",
    "%=": "MODULO_ASSIGN",
    "<<=": "LEFT_SHIFT_ASSIGN",
    ">>=": "RIGHT_SHIFT_ASSIGN",
    ">>>=": "UNSIGNED_RIGHT_SHIFT_ASSIGN",
    "&=": "AND_ASSIGN",
    "|=": "OR_ASSIGN",
    "^=": "XOR_ASSIGN",

    //Operadores de comparação
    "==": "EQUALS",
    "!=": "NOT_EQUALS",
    "<": "LESS_THAN",
    ">": "GREATER_THAN",
    "<=": "LESS_THAN_OR_EQUALS",
    ">=": "GREATER_THAN_OR_EQUALS",

    // Operadores logicos
    "&&": "LOGICAL_AND",
    "||": "LOGICAL_OR",
    "!": "LOGICAL_NOT",

    // Pontução
    ";": "SEMICOLON",
    ":": "COMMA",
    ".": "PERIOD",
    "(": "LEFT_PARENTHESIS",
    ")": "RIGHT_PARENTHESIS",
    "{": "LEFT_BRACE",
    "}": "RIGHT_BRACE",
    "[": "LEFT_BRACKET",
    "]": "RIGHT_BRACKET",
    ":": "COLON",
};

var reservedWords = ["abstract", "assert", "boolean",
    "break", "byte", "case", "catch", "char", "class", "const",
    "continue", "default", "do", "double", "else", "extends", "false",
    "final", "finally", "float", "for", "goto", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "native",
    "new", "null", "package", "private", "protected", "public",
    "return", "short", "static", "strictfp", "super", "switch",
    "synchronized", "this", "throw", "throws", "transient", "true",
    "try", "void", "volatile", "while"]
